### ISSUE TITLE
Gtag is missing. Add the `GoogleAnalytics` component to the `Head` component inside `_document.js`.

### ISSUE THREAD

**Issue by krishaamer** [MauricioRobayo/nextjs-google-analytics#114]
Hi @MauricioRobayo thanks for your amazing work on this! I followed your tutorial line-by-line but keep getting this error in the console `Gtag is missing. Add the GoogleAnalytics component to the Head component inside _document.js.`

Any advice?

<img width="781" alt="Screenshot 2022-02-10 at 14 58 02" src="https://user-images.githubusercontent.com/54409/153354153-cb9ca922-d491-49ab-a0a8-d12da8b2ad45.png">

Cheers,
Kris

**Comment by marc-on-github** [comment]
Have you found a solution?

**Comment by MauricioRobayo** [comment]
Hi! Thanks for reporting this. The message was a leftover from an initial implementation but should not affect any behavior.

I have removed the message as it is misleading, should be working fine even if the message was displayed.
