### ISSUE TITLE
Setting user ID?

### ISSUE THREAD

**Issue by Failcookie** [MauricioRobayo/nextjs-google-analytics#143]
I'd like to set the user ID from NextAuth, if possible. Is this something I am able to do with this package?

Thank you!

**Comment by MauricioRobayo** [comment]
Hi!

I'm sorry, that's not currently doable with this package. :(

**Comment by MauricioRobayo** [comment]
Reopening as this could be a nice feature to implement in the future, will keep this issue open in the meanwhile. PRs welcome! :)

**Comment by MauricioRobayo** [comment]
@Failcookie Would you mind providing some more details on how would you expect this to work?

**Comment by MauricioRobayo** [comment]
I have added `userId` to `pageView` and `event` which will send the `user_id` based on [this documentation](https://developers.google.com/analytics/devguides/collection/ga4/user-id?platform=websites).

**Comment by Failcookie** [comment]
That's great to hear! Thank you for adding this!

**Comment by warmwind** [comment]
`userId ` is added to `PageViewOptions`, however, it was not add to `UsePageViewsOptions`. So it cannot be used by the hook `usePageViews `.  
It should be in `UsePageViewsOptions`, right? or  do I miss something?

```javascript
export interface UsePageViewsOptions {
  gaMeasurementId?: string;
  ignoreHashChange?: boolean;
  disabled?: boolean;
}
```

```javascript
type PageViewOptions = {
  title?: string;
  location?: string;
  path?: string;
  sendPageView?: boolean;
  userId?: string;
};
```

**Comment by MauricioRobayo** [comment]
Hello @warmwind ! sorry for the late reply.

The `pageView` function supports more functionality than the hook. The hook is a trimmed down version which will only sends the `path` (https://github.com/MauricioRobayo/nextjs-google-analytics/blob/681ec7fff3f2e97282b2466731c2b74fe784aad4/src/hooks/usePageViews.ts#L25).

You can use `pageView` to create your own custom hook if you need more functionality than the one provided by default.

That been said, there should be no harm in adding an optional `userId` to the `usePageViews` hook and some people might benefit from it.

Would you like to open a PR adding it, @warmwind ?
