### ISSUE TITLE
Module not found after installation

### ISSUE THREAD

**Issue by zanzlender** [MauricioRobayo/nextjs-google-analytics#213]
Using: NextJS v12.2.0 and nextjs-google-analytics v1.2.1.

I get an error right after installing this package. It's installed and I can see the folder in the node_modules/ however it says `Cannot find module nextjs-google-analytics` when I try to import it in _app or any other file.

I'm still kinda new to Next and Typescript so maybe I'm doing something wrong but still I couldn't solve this one :/

**Comment by MauricioRobayo** [comment]
Hello @zanzlender !

Could you please share more details or a reproducible example? Which version are you using?

**Comment by MauricioRobayo** [comment]
Can I close this issue?

**Comment by zanzlender** [comment]
> Can I close this issue?

My B, will close it now
