### ISSUE TITLE
Cannot read properties of null (reading 'events') while making production build

### ISSUE THREAD

**Issue by morwalz** [MauricioRobayo/nextjs-google-analytics#247]
Why making production build i am getting this error. I placed the google analytics component in head section. 
TypeError: Cannot read properties of null (reading 'events')
    at usePageViews (/srv/habilelabs/production/frontend/node_modules/nextjs-google-analytics/dist/hooks/usePageViews.js:28:16)

**Comment by CallumJHays** [comment]
Moving it ouside of `<Head />` fixed it for me

**Comment by MauricioRobayo** [comment]
Hi!

Sorry for the late reply.

Which version are you using?

Could you share a reproducible example?

**Comment by MauricioRobayo** [comment]
I believe this might be related to some bad documentation the project used to have.

Could you try upgrading to the latest version and going through the Readme again, the usage has been simplified.

**Comment by MauricioRobayo** [comment]
Is it ok to close this issue?

**Comment by CallumJHays** [comment]
Yeah she'll be 'right
