### ISSUE TITLE
Excellent library!

### ISSUE THREAD

**Issue by ctjlewis** [MauricioRobayo/nextjs-google-analytics#290]
This is not a real issue, you've just done a very nice job with this library. Thanks!

**Comment by MauricioRobayo** [comment]
Wow, thanks @ctjlewis ! This is unexpected and so nice, thank you so much for taking the time to write those kind words.

I'll take this as an example to follow and will do it myself on projects I like. Love what you did!

**Comment by opus131** [comment]
Even if I'm a little late to the party, I'd second the OPs point. Nice work, well done!

**Comment by bclabs-kylian** [comment]
Thank you as well!

**Comment by vegancat** [comment]
Frankly, I don't get it!! some are so lazy that they install a dependency to avoid copy-pasting two <Script /> tags?!!!

**Comment by ctjlewis** [comment]
> Frankly, I don't get it!! some are so lazy that they install a dependency to avoid copy-pasting two <Script /> tags?!!!

You saw a thread of people thanking someone for writing a super simple library that's easy to use and thought to drop in and tell us all that you don't get how modules work.

It's probably easier to just tattoo "dipshit" on your forehead.

**Comment by vegancat** [comment]
You leveled me dude!! Ok, you seem to be quite smart with modules and stuff! tell me what extra stuff it does other than putting two script tags within _page.tsx/_page.jsx

**Comment by ctjlewis** [comment]
> You leveled me dude!! Ok, you seem to be quite smart with modules and stuff! tell me what extra stuff it does other than putting two script tags within _page.tsx/_page.jsx

That's literally all it does. It wraps several lines of boilerplate into one component. This is like 99% of React component modules.

**Comment by vegancat** [comment]
I mean I get it! but it normally makes sense with complex use cases! like state management, typing, and complex context providers.

two tags??? But I understand it makes it super simple to implement GA

**Comment by ctjlewis** [comment]
Yes. And Vercel has added better support for GA since this was written, it was originally faster to just use this lib.

**Comment by vegancat** [comment]
cool stuff caught my eye on GitHub Explorer. Actually, we have one thing in common, we are both lazy😜

**Comment by MauricioRobayo** [comment]
I made this to scratch my own itch about two years ago as this was code that I kept reusing in every new project I started. 

Didn't hurt to share it.

Initially it was very basic as I didn't need too much out of it.

Some people found it useful as it saved them some time, despite it being very simple.

Some people contributed and made it way better that what I initially had.

Some people complained, that's fine.

Some people showed gratitude, that's awesome, probably the best thing that I have gotten out of this.

Most probably I will soon archive this project. It's very hard for me to maintain and there is an RFC for `next/third-party` which, hopefully, will make this library useless: https://github.com/vercel/next.js/discussions/48256

**Comment by MauricioRobayo** [comment]
Nextjs is adding [third party scripts](https://github.com/vercel/next.js/tree/canary/packages/third-parties) support.

They are already working on support for [Google Tag Manager and gtag](https://github.com/vercel/next.js/discussions/53868)

That will become the recommended way to add Google Analytics and this package will no longer be needed.

I will soon add a note in the README.

Nextjs has evolved a lot since this packaged was written, at first there was not clear way on how to do this, but that's no longer the case.

Thanks once more @ctjlewis for opening this issue! I'll close it now.
