### ISSUE TITLE
How I can use gtag's consent config options? (GDPR compliance)

### ISSUE THREAD

**Issue by nguaman** [MauricioRobayo/nextjs-google-analytics#349]
Hello, 
first thanks you for this component! 

I am trying to comply the GDPR but with the default option is not possible.

I need to be able to set consent in gtag:

https://developers.google.com/tag-platform/devguides/consent 

```
gtag('consent', 'default', {
  'ad_storage': 'denied',
  'analytics_storage': 'denied'
});
```
I need to be able to deny the creation of cookies by default in gtag so that only when the user accepts the use of cookies can they be created.

In short, the following happens to me:

https://stackoverflow.com/questions/60173853/how-to-set-the-google-analytics-cookie-only-after-another-consent-cookie-is-set

Thanks!

**Comment by nguaman** [comment]
unfortunately I didn't end up using this component.

I solve this issue in this way.

I started by denying access to store cookies.

```
              <Script
                id="gtag-init"
                strategy="afterInteractive"
                dangerouslySetInnerHTML={{
                  __html: `
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('consent', 'default', {
                      'ad_storage': 'denied',
                      'analytics_storage': 'denied'
                    }); 
                      
                    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
                      page_path: window.location.pathname,
                    });
                  `,
                }}
              />
```

And then in my function that accepts the use of cookies, I update the permission.

https://github.com/Mastermindzh/react-cookie-consent#installation

```
              <CookieConsent
                onAccept={handleAcceptCookie}
                enableDeclineButton
                style={{ background: "#0F172A" }}
              >
                This website uses cookies to enhance the user experience.
              </CookieConsent>
```

```
  const handleAcceptCookie = () => {

    window.gtag('consent', 'update', {
      'ad_storage': 'granted',
      'analytics_storage': 'granted'
    });

  };
```

It worked without a problem.

I would love to continue using this library, I will try to find free time to generate a PR.

Thanks!

**Comment by MauricioRobayo** [comment]
https://github.com/MauricioRobayo/nextjs-google-analytics/pull/367

**Comment by nguaman** [comment]
Thanks you! @MauricioRobayo
