### ISSUE TITLE
Ability to set gaMeasurementId without environment variable

### ISSUE THREAD

**Issue by corygibbons** [MauricioRobayo/nextjs-google-analytics#72]
Hey, thanks for the great library it's been helpful.

I'm working on a project where it'd be nice if we could pass in the `gaMeasurementId` as a prop instead of relying on the environment variable, as we'd like to pull the measurement ID from the CMS at build time. Any interest in this as a feature? If so I'm happy to try and open a PR for it.

**Comment by MauricioRobayo** [comment]
Hi @corygibbons, sounds like a great idea, please go ahead with it.

**Comment by coltenkrauter** [comment]
This would be helpful for the case that the NextJS app is deployed via AWS Lambda@Edge Functions which don't allow setting environment variables via CDK configuration.
